### ISSUE TITLE
A small license problem

### ISSUE THREAD

**Issue by ryonakano** [Bat41/toml-glib#4]
The [`meson.build`](https://github.com/AnaGelez/toml-glib/blob/7af6c0cc374ad0418fb62a50e68ca0a925c7fd6b/meson.build#L3) file says MIT, while the [`LICENSE`](https://github.com/AnaGelez/toml-glib/blob/master/LICENSE) file says GPL-3. I guess we may want to unify the license to either one (or possibly another one like LGPL-3).

**Comment by elegaanz** [comment]
Ah, yes… Someone asked me the other day what the license was, and I didn't saw I already chose MIT in the meson.build, so I added the GPL. I would prefer to keep the GPL, so I will fix the meson.build. Thanks for telling me!
